version: "2"

run:
    modules-download-mode: readonly

linters:
    default: none
    enable:
        - depguard
        - errcheck
        - govet
        - ineffassign
        - staticcheck
        - unconvert
        - unparam
        - unused
    exclusions:
      presets:
          - comments
          - common-false-positives
          - legacy
          - std-error-handling
    settings:
      staticcheck:
        checks:
          - all
          - -QF*
          - -ST1003
          - -ST1005
          - -ST1008
          - -ST1012
          - -ST1016
          - -ST1018
          - -ST1023
      depguard:
        rules:
          cmdutils-only-in-commands:
            files:
              - "**/*.go"
              - "!**/cmd/glab/*.go"
              - "!**/internal/testing/cmdtest/*.go"
              - "!**/internal/commands/*.go"
              - "!**/internal/commands/**/*.go"
            deny:
              - pkg: "gitlab.com/gitlab-org/cli/internal/cmdutils"
                desc: "internal/cmdutils should only be imported from packages under internal/commands/"

          no-testing-in-production:
            files:
              - "!$test"
            deny:
              - pkg: "gitlab.com/gitlab-org/cli/internal/testing/**"
                desc: "Testing utilities should only be used in test files"

formatters:
    enable:
        - gofumpt
        - goimports
