version: "2"

run:
    modules-download-mode: readonly

linters:
    default: none
    enable:
        - errcheck
        - govet
        - ineffassign
        - staticcheck
        - unused
    exclusions:
      presets:
          - comments
          - common-false-positives
          - legacy
          - std-error-handling
    settings:
      staticcheck:
        checks:
          - all
          - -QF*
          - -ST1003
          - -ST1005
          - -ST1008
          - -ST1012
          - -ST1016
          - -ST1018
          - -ST1023

formatters:
    enable:
        - gofumpt
        - goimports
