project_name: glab
version: 2

release:
  prerelease: auto
  extra_files:
    - glob: "./bin/*.exe"

before:
  hooks:
    - go mod tidy
    - go mod vendor
    - make manpage

builds:
  - <<: &build_defaults
      main: ./cmd/glab
      binary: bin/glab
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X main.version=v{{.Version}} -X main.commit={{.ShortCommit}} -X "main.goversion={{.Env.GO_VERSION}}"
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    hooks:
      post:
        - cmd: './scripts/sign-binary.sh macos "{{ .Path }}"'
          output: true

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: ["386", arm, amd64, arm64, ppc64le, s390x]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: ["386", amd64]
    hooks:
      post:
        - cmd: './scripts/sign-binary.sh windows "{{ .Path }}"'
          output: true

  - <<: *build_defaults
    id: freebsd
    goos: [freebsd]
    goarch: ["386", amd64, arm]

gitlab_urls:
  use_job_token: true
  use_package_registry: true

dockers:
  - image_templates:
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-amd64"
      - "gitlab/glab:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-arm64"
      - "gitlab/glab:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}"
    image_templates:
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-amd64"
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-arm64"
  - name_template: "registry.gitlab.com/gitlab-org/cli:latest"
    image_templates:
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-amd64"
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-arm64"
  - name_template: "gitlab/glab:{{ .Tag }}"
    image_templates:
      - "gitlab/glab:{{ .Tag }}-amd64"
      - "gitlab/glab:{{ .Tag }}-arm64"
  - name_template: "gitlab/glab:latest"
    image_templates:
      - "gitlab/glab:{{ .Tag }}-amd64"
      - "gitlab/glab:{{ .Tag }}-arm64"

archives:
  - id: nix
    ids: [macos, linux, freebsd]
    wrap_in_directory: false

  - id: windows
    ids: [windows]
    formats: zip

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: tar.gz
  files:
    - vendor/*

nfpms:
  - id: foo
    package_name: glab

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults to all builds.

    vendor: GitLab
    homepage: https://gitlab.com/gitlab-org/cli
    # using service-desk email https://docs.gitlab.com/user/project/service_desk/
    maintainer: GitLab<contact-project+gitlab-org-cli-34675721-issue-@incoming.gitlab.com>
    description: An open source GitLab CLI tool
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - git
    bindir: /usr
    contents:
      - src: "./share/man/man1/glab*.1"
        dst: "/usr/share/man/man1"

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: ./bin/*installer.exe

snapshot:
  version_template: "{{ .Tag }}"
changelog:
  # https://goreleaser.com/customization/changelog/
  use: gitlab
  sort: asc
  filters:
    exclude:
      - "^Merge branch"
      - "^Update README.md"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Maintenance
      regexp: '^.*?(chore|ci|refactor)(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Dependencies
      regexp: '^.*?chore\((deps|dependencies)\)[^:]*:.+$'
      order: 4
    - title: Others
      order: 999

announce:
  slack:
    enabled: true
    # Set SLACK_WEBHOOK environment variable in your CI/CD settings
    # Format: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXX
    channel: '{{ .Env.SLACK_CHANNEL }}'
    username: 'glab Release Bot'
    icon_emoji: ':rocket:'
    message_template: |
      :rocket: *glab {{ .Tag }}* has been released!
      {{ if .IsPrerelease }}
      :warning: _This is a pre-release version_
      {{ end }}
      *What's Changed*
      {{ range .Changelog.Groups -}}
      {{ if gt (len .Items) 0 -}}
      *{{ .Title }}*
      {{ range .Items -}}
      • {{ .Message }} - <{{ .WebURL }}|{{ .ShortHash }}>{{ if .AuthorName }} by {{ .AuthorName }}{{ if .AuthorEmail }} <{{ .AuthorEmail }}>{{ end }}{{ end }}
      {{ end }}
      {{ end -}}
      {{ end }}
      *Get the Release*
      • <{{ .ReleaseURL }}|View on GitLab>
      • <https://gitlab.com/gitlab-org/cli/-/releases/{{ .Tag }}|Download Assets>
