project_name: glab
version: 2

release:
  prerelease: auto
  extra_files:
    - glob: "./bin/*.exe"

before:
  hooks:
    - go mod tidy
    - go mod vendor
    - make manpage

builds:
  - <<: &build_defaults
      main: ./cmd/glab
      binary: bin/glab
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X main.version=v{{.Version}} -X main.commit={{.ShortCommit}} -X "main.goversion={{.Env.GO_VERSION}}"
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: ["386", arm, amd64, arm64, ppc64le, s390x]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: ["386", amd64]

  - <<: *build_defaults
    id: freebsd
    goos: [freebsd]
    goarch: ["386", amd64, arm]

gitlab_urls:
  use_job_token: true
  use_package_registry: true

dockers:
  - image_templates:
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-amd64"
      - "gitlab/glab:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-arm64"
      - "gitlab/glab:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}"
    image_templates:
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-amd64"
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-arm64"
  - name_template: "registry.gitlab.com/gitlab-org/cli:latest"
    image_templates:
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-amd64"
      - "registry.gitlab.com/gitlab-org/cli:{{ .Tag }}-arm64"
  - name_template: "gitlab/glab:{{ .Tag }}"
    image_templates:
      - "gitlab/glab:{{ .Tag }}-amd64"
      - "gitlab/glab:{{ .Tag }}-arm64"
  - name_template: "gitlab/glab:latest"
    image_templates:
      - "gitlab/glab:{{ .Tag }}-amd64"
      - "gitlab/glab:{{ .Tag }}-arm64"

archives:
  - id: nix
    ids: [macos, linux, freebsd]
    wrap_in_directory: false

  - id: windows
    ids: [windows]
    formats: zip

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: tar.gz
  files:
    - vendor/*

nfpms:
  - id: foo
    package_name: glab

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults to all builds.

    vendor: GitLab
    homepage: https://gitlab.com/gitlab-org/cli
    # using service-desk email https://docs.gitlab.com/user/project/service_desk/
    maintainer: GitLab<contact-project+gitlab-org-cli-34675721-issue-@incoming.gitlab.com>
    description: An open source GitLab CLI tool
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - git
    bindir: /usr
    contents:
      - src: "./share/man/man1/glab*.1"
        dst: "/usr/share/man/man1"

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: ./bin/*installer.exe

snapshot:
  version_template: "{{ .Tag }}"
changelog:
  # https://goreleaser.com/customization/changelog/
  use: gitlab
  sort: asc
  filters:
    exclude:
      - >
        ^docs(\(.*\))*:
      - >
        ^test(\(.*\))*:
      - "^Merge branch"
      - "^chore"
      - "^Update README.md"

binary_signs:
  - id: code-signer
    cmd: sh
    signature: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}.sha256'
    args:
      - -c
      # This could be simplified if we built an image that had a combination of code-signer
      # and goreleaser. Note that goreleaser Pro contains the conditional `if` block, but
      # since the open source version does not we have to implement this logic in the script.
      # We have to ensure we pass all the required secrets and configuration to code-signer.
      - |
        artifact="${artifact}"
        if echo "$artifact" | grep -qE 'windows|\.exe$'; then
          echo "Signing Windows binary: $artifact"
          docker run \
            --rm \
            -e "GCLOUD_PROJECT={{ .Env.GCLOUD_PROJECT }}" \
            -e "GOOGLE_APPLICATION_CREDENTIALS={{ .Env.GOOGLE_APPLICATION_CREDENTIALS }}" \
            -v "{{ .Env.HOST_PWD }}/.gitlab-secrets:/var/run/secrets/gitlab" \
            -v "{{ .Env.HOST_PWD }}:/work" \
            registry.gitlab.com/gitlab-com/gl-infra/common-ci-tasks-images/code-signer:1.2.1 \
            sign-windows-binaries --overwrite "/work/$artifact"
        elif echo "$artifact" | grep -qE 'darwin|macos'; then
          echo "Signing macOS binary: $artifact"
          docker run \
            --rm \
            -e "APPSTORE_CONNECT_API_KEY_FILE={{ .Env.APPSTORE_CONNECT_API_KEY_FILE }}" \
            -e "GCLOUD_PROJECT={{ .Env.GCLOUD_PROJECT }}" \
            -e "GOOGLE_APPLICATION_CREDENTIALS={{ .Env.GOOGLE_APPLICATION_CREDENTIALS }}" \
            -v "{{ .Env.HOST_PWD }}/.gitlab-secrets:/var/run/secrets/gitlab" \
            -v "{{ .Env.HOST_PWD }}:/work" \
            -v "{{ .Env.APPSTORE_CONNECT_API_KEY_FILE }}:{{ .Env.APPSTORE_CONNECT_API_KEY_FILE }}" \
            registry.gitlab.com/gitlab-com/gl-infra/common-ci-tasks-images/code-signer:1.2.1 \
            sign-macos-binaries --overwrite "/work/$artifact"
        else
          echo "Not a Windows or macOS binary, no need for code signing: $artifact"
        fi
        echo "Generating SHA-256 checksum for ${artifact} -> ${signature}"
        sha256sum "${artifact}" > "${signature}"
        ls -al "${artifact}" "${signature}"
    output: true
