// Code generated by gen/main.go. DO NOT EDIT.
// Check the internal/config/Readme.md on how to add or modify the config stub.

package config

import (
	"gopkg.in/yaml.v3"
)

func rootConfig() *yaml.Node {
	return &yaml.Node{
		Kind: yaml.DocumentNode,
		Content: []*yaml.Node{
			{
				Kind: yaml.MappingNode,
				Content: []*yaml.Node{
					{
						HeadComment: "# What protocol to use when performing Git operations. Supported values: ssh, https.",
						Kind:        yaml.ScalarNode,
						Value:       "git_protocol",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "ssh",
					},
					{
						HeadComment: "# What editor glab should run when creating issues, merge requests, etc. This global config cannot be overridden by hostname.",
						Kind:        yaml.ScalarNode,
						Value:       "editor",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# What browser glab should run when opening links. This global config cannot be overridden by hostname.",
						Kind:        yaml.ScalarNode,
						Value:       "browser",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# Set your desired Markdown renderer style. Available options are [dark, light, notty]. To set a custom style, refer to https://github.com/charmbracelet/glamour#styles",
						Kind:        yaml.ScalarNode,
						Value:       "glamour_style",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "dark",
					},
					{
						HeadComment: "# Allow glab to automatically check for updates and notify you when there are new updates.",
						Kind:        yaml.ScalarNode,
						Value:       "check_update",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "true",
					},
					{
						HeadComment: "# Whether or not to display hyperlink escape characters when listing items like issues or merge requests. Set to TRUE to display hyperlinks in TTYs only. Force hyperlinks by setting FORCE_HYPERLINKS=1 as an environment variable.",
						Kind:        yaml.ScalarNode,
						Value:       "display_hyperlinks",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "false",
					},
					{
						HeadComment: "# Default GitLab hostname to use.",
						Kind:        yaml.ScalarNode,
						Value:       "host",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "gitlab.com",
					},
					{
						HeadComment: "# Set to true (1) to disable prompts, or false (0) to enable them.",
						Kind:        yaml.ScalarNode,
						Value:       "no_prompt",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "false",
					},
					{
						HeadComment: "# Configuration specific for GitLab instances.",
						Kind:        yaml.ScalarNode,
						Value:       "hosts",
					},
					{
						Kind: yaml.MappingNode,
						Content: []*yaml.Node{
							{
								Kind:  yaml.ScalarNode,
								Value: "gitlab.com",
							},
							{
								Kind: yaml.MappingNode,
								Content: []*yaml.Node{
									{
										HeadComment: "# What protocol to use to access the API endpoint. Supported values: http, https.",
										Kind:        yaml.ScalarNode,
										Value:       "api_protocol",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "https",
									},
									{
										HeadComment: "# Configure host for API endpoint. Defaults to the host itself.",
										Kind:        yaml.ScalarNode,
										Value:       "api_host",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "gitlab.com",
									},
									{
										HeadComment: "# Your GitLab access token. To get one, read https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html",
										Kind:        yaml.ScalarNode,
										Value:       "token",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "",
									},
								},
							},
						},
					},
					{
						HeadComment: "# Use aliases to create nicknames for glab commands. Supports shell-executable aliases that may not be glab commands.",
						Kind:        yaml.ScalarNode,
						Value:       "aliases",
					},
					{
						Kind: yaml.MappingNode,
						Content: []*yaml.Node{
							{
								Kind:  yaml.ScalarNode,
								Value: "ci",
							},
							{
								Kind:  yaml.ScalarNode,
								Value: "pipeline ci",
							},
							{
								Kind:  yaml.ScalarNode,
								Value: "co",
							},
							{
								Kind:  yaml.ScalarNode,
								Value: "mr checkout",
							},
						},
					},
				},
			},
		},
	}
}
